#!/bin/bash
# Manual Testing Guide for GPS Tracking & Location History
# Run this in browser console after logging in

echo "📍 Manual Testing Guide - GPS Tracking & Location History"
echo "=========================================================="
echo ""
echo "🔗 Services Status:"
echo "   Backend:  http://localhost:8080/actuator/health"
echo "   Frontend: http://localhost:4200"
echo ""

# Check if services are running
BACKEND_STATUS=$(curl -s http://localhost:8080/actuator/health 2>/dev/null | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
FRONTEND_STATUS=$(curl -s http://localhost:4200 2>/dev/null | grep -q "SV-TMS" && echo "UP" || echo "DOWN")

if [ "$BACKEND_STATUS" = "UP" ]; then
    echo "   ✅ Backend: UP"
else
    echo "   ❌ Backend: $BACKEND_STATUS"
    echo "   Run: cd tms-backend && ./mvnw spring-boot:run"
fi

if [ "$FRONTEND_STATUS" = "UP" ]; then
    echo "   ✅ Frontend: UP"
else
    echo "   ❌ Frontend: DOWN"
    echo "   Run: cd tms-frontend && npm start"
fi

echo ""
echo "=========================================================="
echo "TEST 1: Driver Location History Page"
echo "=========================================================="
echo ""
echo "1. Open: http://localhost:4200/login"
echo "   Login: admin@svtrucking.com / admin123"
echo ""
echo "2. Navigate to: http://localhost:4200/drivers/30210/location-history"
echo ""
echo "3. Expected Features:"
echo "   ✓ Date range picker (default: last 7 days)"
echo "   ✓ Google Map with driver's route polyline"
echo "   ✓ Location markers with timestamps"
echo "   ✓ Speed and distance statistics"
echo "   ✓ Loading indicator while fetching data"
echo ""
echo "4. API Call (check Network tab):"
echo "   GET /api/admin/drivers/30210/location-history?days=7"
echo "   Authorization: Bearer <token>"
echo ""

echo "=========================================================="
echo "TEST 2: GPS Tracking with Real-Time Alerts"
echo "=========================================================="
echo ""
echo "1. Navigate to: http://localhost:4200/live/drivers"
echo ""
echo "2. Open Browser DevTools (F12 or Cmd+Option+I)"
echo "   Switch to Console tab"
echo ""
echo "3. Paste these commands to test alerts:"
echo ""
echo "   // Get component reference"
echo '   const comp = ng.getComponent(document.querySelector("app-driver-gps-tracking"));'
echo ""
echo "   // Test speeding alert (Yellow toast)"
echo "   comp.driverAlertService.checkAndEmitAlerts(1, { speed: 95 });"
echo ""
echo "   // Test battery low alert (Red toast)"
echo "   comp.driverAlertService.checkAndEmitAlerts(2, { batteryLevel: 10 });"
echo ""
echo "   // Test harsh braking (Red toast)"
echo "   comp.driverAlertService.checkAndEmitAlerts(3, { acceleration: -7 });"
echo ""
echo "4. Expected Behavior:"
echo "   ✓ Toast appears in top-right corner"
echo "   ✓ Slide-in animation (300ms)"
echo "   ✓ Color coding:"
echo "     - Red: Critical (battery <15%, harsh braking)"
echo "     - Yellow: Warning (speeding >80 km/h)"
echo "     - Blue: Info"
echo "   ✓ Snooze button → hides for 5 minutes"
echo "   ✓ Dismiss (✕) → removes immediately"
echo "   ✓ Duplicate alerts blocked for 30 seconds"
echo ""
echo "5. Test Multiple Alerts:"
echo "   comp.driverAlertService.checkAndEmitAlerts(1, { speed: 95 });"
echo "   comp.driverAlertService.checkAndEmitAlerts(2, { batteryLevel: 8 });"
echo "   comp.driverAlertService.checkAndEmitAlerts(3, { speed: 110 });"
echo "   → 3 toasts should stack vertically"
echo ""
echo "6. Test Cooldown (30 seconds):"
echo "   comp.driverAlertService.checkAndEmitAlerts(1, { speed: 100 });"
echo "   comp.driverAlertService.checkAndEmitAlerts(1, { speed: 105 });"
echo "   → Second alert should be blocked"
echo "   console.log('Active alerts:', comp.driverAlertService.getActiveAlerts().size);"
echo "   → Should show 1 (not 2)"
echo ""

echo "=========================================================="
echo "TEST 3: WebSocket Real-Time Updates"
echo "=========================================================="
echo ""
echo "1. Still on: http://localhost:4200/live/drivers"
echo ""
echo "2. Open Network tab in DevTools"
echo "   Filter: WS (WebSocket)"
echo ""
echo "3. Expected Connections:"
echo "   ✓ ws://localhost:8080/ws (or /ws-sockjs/...)"
echo "   ✓ Status: 101 Switching Protocols"
echo "   ✓ Green indicator (connected)"
echo ""
echo "4. Monitor Messages:"
echo "   Click on WebSocket connection"
echo "   → Messages tab"
echo "   → Should see STOMP frames"
echo "   → CONNECTED, SUBSCRIBE, MESSAGE frames"
echo ""
echo "5. Test Reconnection:"
echo "   // In console:"
echo "   comp.driverLocationService.disconnect();"
echo "   // Wait 2 seconds"
echo "   comp.driverLocationService.connect();"
echo "   → Should reconnect with exponential backoff"
echo ""

echo "=========================================================="
echo "TEST 4: Marker Clustering (Zoom-Aware)"
echo "=========================================================="
echo ""
echo "1. On: http://localhost:4200/live/drivers"
echo ""
echo "2. Zoom OUT on map (zoom level < 13):"
echo "   → Markers should cluster into groups"
echo "   → Green clusters: ≥50% drivers online"
echo "   → Red clusters: <50% drivers online"
echo ""
echo "3. Zoom IN on map (zoom level ≥ 13):"
echo "   → Clusters should expand to individual markers"
echo ""
echo "4. Console Commands:"
echo "   // Get current zoom"
echo "   comp.map.getZoom()"
echo ""
echo "   // Check clustering status"
echo "   console.log('Clustering enabled:', comp.clusteringEnabled);"
echo "   console.log('Clusterer exists:', !!comp.markerClusterer);"
echo ""

echo "=========================================================="
echo "VERIFICATION CHECKLIST"
echo "=========================================================="
echo ""
echo "Location History:"
echo "  [ ] Route loads without errors"
echo "  [ ] Authentication required (redirects if not logged in)"
echo "  [ ] Map displays polyline route"
echo "  [ ] Date picker changes data range"
echo "  [ ] API call returns location array"
echo ""
echo "GPS Tracking Alerts:"
echo "  [ ] Toast appears top-right"
echo "  [ ] Correct color for severity"
echo "  [ ] Snooze button works"
echo "  [ ] Dismiss button works"
echo "  [ ] Cooldown prevents duplicates"
echo "  [ ] Multiple alerts stack vertically"
echo ""
echo "WebSocket:"
echo "  [ ] Connection established"
echo "  [ ] Messages flow in real-time"
echo "  [ ] Reconnects after disconnect"
echo "  [ ] Circuit breaker activates on auth failure"
echo ""
echo "Marker Clustering:"
echo "  [ ] Clusters at low zoom (<13)"
echo "  [ ] Individual markers at high zoom (≥13)"
echo "  [ ] Smooth transitions on zoom change"
echo "  [ ] Color coding reflects online status"
echo ""
echo "=========================================================="
echo "📊 Performance Expectations"
echo "=========================================================="
echo ""
echo "  Marker rendering: <800ms for 400 drivers"
echo "  Frame rate: 60fps during pan/zoom"
echo "  WebSocket latency: <100ms"
echo "  Alert cooldown: 30 seconds per type"
echo "  Cluster update: <20ms per zoom change"
echo ""
echo "=========================================================="
echo "✅ All automated tests passed!"
echo "🧪 Ready for manual browser testing"
echo "=========================================================="
