package com.svtrucking.logistics.service;

import com.svtrucking.logistics.model.Dispatch;
import com.svtrucking.logistics.model.LoadingQueue;
import com.svtrucking.logistics.model.PreLoadingSafetyCheck;
import com.svtrucking.logistics.repository.DispatchRepository;
import com.svtrucking.logistics.repository.LoadingQueueRepository;
import com.svtrucking.logistics.repository.PreLoadingSafetyCheckRepository;
import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.NoSuchElementException;

@Service
@RequiredArgsConstructor
public class SafetyChecklistPdfService {

  private final PreLoadingSafetyCheckRepository safetyRepo;
  private final DispatchRepository dispatchRepo;
  private final LoadingQueueRepository loadingQueueRepository;

  public byte[] generate(Long dispatchId) {
    Dispatch dispatch =
        dispatchRepo
            .findById(dispatchId)
            .orElseThrow(() -> new NoSuchElementException("Dispatch not found: " + dispatchId));
    PreLoadingSafetyCheck check =
        safetyRepo
            .findTopByDispatchIdOrderByCheckedAtDesc(dispatchId)
            .orElseThrow(
                () -> new NoSuchElementException("No safety check found for dispatch " + dispatchId));
    LoadingQueue queue = loadingQueueRepository.findByDispatchId(dispatchId).orElse(null);

    try (PDDocument doc = new PDDocument()) {
      PDPage page = new PDPage(PDRectangle.A4);
      doc.addPage(page);

      try (PDPageContentStream content = new PDPageContentStream(doc, page)) {
        float y = 800;
        content.setFont(PDType1Font.HELVETICA_BOLD, 18);
        content.beginText();
        content.newLineAtOffset(50, y);
        content.showText("PRE-LOADING SAFETY CHECKLIST");
        content.endText();

        y -= 30;
        content.setFont(PDType1Font.HELVETICA, 12);

        drawLine(content, 50, y, detail("Dispatch No", safe(dispatch.getRouteCode())));
        y -= 16;
        drawLine(content, 50, y, detail("Driver", safe(dispatch.getDriver() != null ? dispatch.getDriver().getName() : "N/A")));
        y -= 16;
        drawLine(content, 50, y, detail("Truck", safe(dispatch.getVehicle() != null ? dispatch.getVehicle().getLicensePlate() : "N/A")));
        y -= 16;
        drawLine(content, 50, y, detail("Warehouse", queue != null && queue.getWarehouseCode() != null ? queue.getWarehouseCode().name() : "N/A"));
        y -= 16;
        drawLine(content, 50, y, detail("Checked At", formatDate(check.getCheckedAt())));
        y -= 24;

        content.setFont(PDType1Font.HELVETICA_BOLD, 12);
        drawLine(content, 50, y, "Checklist (OK / NOT OK)");
        y -= 18;
        content.setFont(PDType1Font.HELVETICA, 12);

        y = drawChecklistRow(content, y, "Driver PPE", check.isDriverPpeOk());
        y = drawChecklistRow(content, y, "Fire Extinguisher", check.isFireExtinguisherOk());
        y = drawChecklistRow(content, y, "Wheel Chock", check.isWheelChockOk());
        y = drawChecklistRow(content, y, "Truck Leakage", check.isTruckLeakageOk());
        y = drawChecklistRow(content, y, "Truck Cleanliness", check.isTruckCleanOk());
        y = drawChecklistRow(content, y, "Truck Condition", check.isTruckConditionOk());

        y -= 20;
        content.setFont(PDType1Font.HELVETICA_BOLD, 12);
        drawLine(content, 50, y, "Result: " + check.getResult());
        y -= 16;

        if (check.getFailReason() != null && !check.getFailReason().isBlank()) {
          content.setFont(PDType1Font.HELVETICA, 12);
          drawLine(content, 50, y, "Fail Reason: " + check.getFailReason());
          y -= 16;
        }

        y -= 20;
        content.setFont(PDType1Font.HELVETICA_BOLD, 12);
        drawLine(content, 50, y, "Signatures");
        y -= 16;
        content.setFont(PDType1Font.HELVETICA, 12);
        drawLine(content, 50, y, "Officer: _________________________      Date: __________");
        y -= 16;
        drawLine(content, 50, y, "Driver:  _________________________      Date: __________");

        y -= 30;
        content.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
        drawLine(content, 50, y, "[QR CODE]");
        y -= 14;
        drawLine(content, 50, y, "Generated by SV TMS / បង្កើតដោយ ប្រព័ន្ធ SV TMS");
      }

      ByteArrayOutputStream out = new ByteArrayOutputStream();
      doc.save(out);
      return out.toByteArray();
    } catch (IOException e) {
      throw new RuntimeException("Failed to generate safety checklist PDF", e);
    }
  }

  private void drawLine(PDPageContentStream content, float x, float y, String text) throws IOException {
    content.beginText();
    content.newLineAtOffset(x, y);
    content.showText(text);
    content.endText();
  }

  private float drawChecklistRow(PDPageContentStream content, float y, String label, boolean ok)
      throws IOException {
    drawLine(content, 50, y, "- " + label + ": " + (ok ? "OK" : "NOT OK"));
    return y - 14;
  }

  private String detail(String label, String value) {
    return label + ": " + value;
  }

  private String safe(String value) {
    return value == null || value.isBlank() ? "N/A" : value;
  }

  private String formatDate(java.time.LocalDateTime time) {
    if (time == null) return "N/A";
    return time.format(DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm"));
  }
}
