#!/bin/bash
# Phase 3 Testing Guide - Real-Time Alerts
# Run this to understand how to test the alert system on localhost:4200

set -e

echo "=========================================="
echo "Phase 3: Real-Time Alerts Testing Guide"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "  ✓ npm start running on localhost:4200"
echo "  ✓ Backend API running on localhost:8080"
echo "  ✓ WebSocket connection active"
echo ""
echo "Testing Checklist:"
echo ""
echo "1. VERIFY ALERT COMPONENTS LOADED"
echo "   - Navigate to http://localhost:4200/live/drivers"
echo "   - Open Chrome DevTools (F12)"
echo "   - Go to Console tab"
echo "   - Type: document.querySelectorAll('app-driver-alert-toast').length"
echo "   - Expected: 0 (no alerts yet)"
echo ""

echo "2. TEST SPEEDING ALERT (Speed > 80 km/h)"
echo "   Method A: Backend Simulation"
echo "   - Run: curl -X POST http://localhost:8080/api/admin/drivers/1/speed-sim -d '{\"speed\": 95}'"
echo "   - Expected: Yellow toast appears top-right saying 'Driver 1 speeding: 95 km/h'"
echo "   - Expected: Toast disappears after 5 seconds (auto-close)"
echo ""
echo "   Method B: Browser Console (Mock)"
echo "   - Open Chrome DevTools Console"
echo "   - Paste:"
echo "     const service = ng.getComponent(document.querySelector('app-driver-gps-tracking')).driverAlertService;"
echo "     service.checkAndEmitAlerts(1, { speed: 95, batteryLevel: 75 });"
echo "   - Expected: Yellow toast appears immediately"
echo ""

echo "3. TEST COOLDOWN ENFORCEMENT (No spam within 30s)"
echo "   - Trigger same alert 3 times quickly"
echo "   - Expected: Toast only appears once, next 2 are ignored (check console)"
echo "   - Wait 30 seconds"
echo "   - Trigger again"
echo "   - Expected: Toast appears again (cooldown expired)"
echo ""

echo "4. TEST HARSH BRAKING ALERT (Acceleration < -6 m/s²)"
echo "   - Paste in Console:"
echo "     service.checkAndEmitAlerts(2, { acceleration: -7.5, speed: 50 });"
echo "   - Expected: Yellow toast with 'harsh braking: 7.5 m/s²'"
echo ""

echo "5. TEST BATTERY LOW ALERT (Battery < 15%)"
echo "   - Paste in Console:"
echo "     service.checkAndEmitAlerts(3, { batteryLevel: 12, speed: 40 });"
echo "   - Expected: Yellow toast with 'battery low: 12%'"
echo ""

echo "6. TEST SNOOZE BUTTON"
echo "   - Trigger speeding alert (or wait for one)"
echo "   - Click 'Snooze' button on toast"
echo "   - Expected: Toast disappears"
echo "   - Expected: Alert removed from activeAlerts map"
echo "   - Check console: ng.getComponent(...).activeAlerts.size → should decrease"
echo ""

echo "7. TEST DISMISS BUTTON"
echo "   - Trigger another alert"
echo "   - Click '✕' (dismiss) button"
echo "   - Expected: Toast immediately disappears"
echo "   - Expected: Alert removed from activeAlerts map"
echo ""

echo "8. TEST TOAST STYLING"
echo "   - All toasts should:"
echo "     • Appear in top-right corner"
echo "     • Have yellow background (warning severity)"
echo "     • Have white text"
echo "     • Slide in smoothly from right (300ms animation)"
echo "     • Show timestamp using current time"
echo "   - Open DevTools Elements tab"
echo "   - Inspect <app-driver-alert-toast> element"
echo "   - Verify Tailwind classes applied:"
echo "     bg-yellow-100, border-l-4, border-yellow-500, text-yellow-800"
echo ""

echo "9. TEST MULTIPLE ALERTS (UI Stack)"
echo "   - Trigger 3+ different alerts quickly"
echo "   - Expected: Each toast stacks on top (may overlap)"
echo "   - Expected: Each has independent snooze/dismiss"
echo ""

echo "10. TEST ALERT HISTORY"
echo "    - Open Console and run:"
echo "      const service = ng.getComponent(document.querySelector('app-driver-gps-tracking')).driverAlertService;"
echo "      service.alerts$.value"
echo "    - Expected: Logged array of all alerts triggered (up to 100)"
echo "    - Expected: Each has id, driverId, type, severity, timestamp, message"
echo ""

echo "=========================================="
echo "Console Helper Commands"
echo "=========================================="
echo ""
echo "Get component reference:"
echo "  const comp = ng.getComponent(document.querySelector('app-driver-gps-tracking'));"
echo ""
echo "Trigger speeding alert:"
echo "  comp.driverAlertService.checkAndEmitAlerts(1, { speed: 95 });"
echo ""
echo "Check active alerts:"
echo "  comp.activeAlerts"
echo ""
echo "Trigger all alert types:"
echo "  comp.driverAlertService.checkAndEmitAlerts(1, {"
echo "    speed: 95,"
echo "    batteryLevel: 12,"
echo "    acceleration: -7"
echo "  });"
echo ""
echo "View alert history:"
echo "  comp.driverAlertService.alerts$.value"
echo ""
echo "Clear all alerts:"
echo "  comp.driverAlertService.activeAlerts$.value.clear();"
echo "  comp.driverAlertService.activeAlerts$.next(new Map());"
echo ""

echo "=========================================="
echo "Expected Alert Colors & Icons"
echo "=========================================="
echo ""
echo "CRITICAL (🔴 Red):"
echo "  Background: bg-red-100"
echo "  Border: border-red-500"
echo "  Text: text-red-800"
echo ""
echo "WARNING (🟡 Yellow) [Current default]:"
echo "  Background: bg-yellow-100"
echo "  Border: border-yellow-500"
echo "  Text: text-yellow-800"
echo ""
echo "INFO (🔵 Blue):"
echo "  Background: bg-blue-100"
echo "  Border: border-blue-500"
echo "  Text: text-blue-800"
echo ""

echo "=========================================="
echo "Debugging"
echo "=========================================="
echo ""
echo "If toasts don't appear:"
echo "  1. Check DevTools Console for errors"
echo "  2. Verify DriverAlertToastComponent imported in component"
echo "  3. Check HTML template has alert toast container"
echo "  4. Run: document.querySelectorAll('app-driver-alert-toast').length"
echo ""
echo "If cooldown isn't working:"
echo "  1. Check DriverAlertService.ALERT_COOLDOWN_MS = 30000"
echo "  2. Verify maybeEmitAlert() checks lastAlertTs map"
echo "  3. Note: Cooldown is per driver AND per alert type"
echo ""
echo "If snooze/dismiss not working:"
echo "  1. Verify toast component emits events"
echo "  2. Check parent component subscribes to (snoozed) and (dismissed)"
echo "  3. Verify dismissAlert() and snoozeAlert() in service"
echo ""

echo "=========================================="
echo "Performance Notes"
echo "=========================================="
echo ""
echo "Alert overhead should be minimal:"
echo "  • Toast render: <5ms"
echo "  • Change detection: OnPush (efficient)"
echo "  • Service: No polling, event-driven"
echo ""
echo "Monitor in DevTools Performance tab:"
echo "  1. Open Performance tab"
echo "  2. Record performance"
echo "  3. Trigger alert"
echo "  4. Stop recording"
echo "  5. Look for app-driver-alert-toast rendering"
echo "  6. Should be <50ms frame time"
echo ""

echo "=========================================="
echo "Next Steps"
echo "=========================================="
echo ""
echo "After verifying all tests pass:"
echo "  1. Create integration test file for alerts"
echo "  2. Test with real driver updates from WebSocket"
echo "  3. Deploy to staging for QA"
echo "  4. Gather feedback on alert frequency/severity"
echo "  5. Plan Phase 4 enhancements (geofencing, custom rules UI)"
echo ""
