import type { OrderAddressDto } from '../services/order-address.model';

export interface Order {
  id?: number; // Optional for new orders
  orderNumber: string;
  orderReference?: string;
  customerName: string;
  billTo?: string;
  deliveryAddress: string;
  pickupAddress?: OrderAddressDto | null;
  dropAddress?: OrderAddressDto | null;
  createdAt?: string; // Auto-generated by backend
  status: string;
  assignedVehicle?: string;
  assignedDriver?: string;
  proofOfDelivery?: string;
  shipments?: any[]; // Ensure shipments are included
  items?: {
    itemName?: string;
    quantity?: number;
    unitOfMeasurement?: string;
    palletType?: string | number;
    fromDestination?: string;
    toDestination?: string;
    warehouse?: string;
  }[];
  dispatches?: {
    id?: number;
    routeCode?: string;
    driverName?: string;
    licensePlate?: string;
    status?: string;
    createdDate?: string;
  }[];
}
