export enum VehicleStatus {
  ACTIVE = 'ACTIVE',
  UNDER_REPAIR = 'UNDER_REPAIR',
  SAFETY_HOLD = 'SAFETY_HOLD',
  RETIRED = 'RETIRED',
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  MAINTENANCE = 'MAINTENANCE',
  IN_ISSUE = 'IN_ISSUE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}
