spring.config.import=optional:classpath:application-backend-common.properties
spring.application.name=tms-driver-app-api
server.port=${SERVER_PORT:8084}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
