package com.svtrucking.logistics.enums;

public enum IncidentType {
  SPEEDING,
  HARSH_BRAKING,
  HARSH_ACCELERATION,
  SHARP_CORNERING,
  WRONG_ROUTE,
  UNPROFESSIONAL_CONDUCT,
  POLICY_VIOLATION,
  UNAUTHORIZED_STOP,
  MISSED_SCHEDULE,
  CUSTOMER_COMPLAINT,
  DAMAGE_CLAIM,
  SERVICE_QUALITY_ISSUE,
  COLLISION,
  PROPERTY_DAMAGE,
  INJURY,
  MECHANICAL_FAILURE,
  BREAKDOWN,
  MAINTENANCE_DUE,
  OTHER
}
