import { PERMISSIONS } from '../../shared/permissions';

import type { SidebarMenuItem } from './sidebar-menu.types';

export const SIDEBAR_MENU_CONFIG: SidebarMenuItem[] = [
  {
    id: 'overview',
    label: 'Overview',
    icon: 'space_dashboard',
    group: 'overview',
    children: [
      {
        label: 'Dashboard',
        icon: 'dashboard',
        route: '/dashboard',
        permission: PERMISSIONS.DASHBOARD_READ,
      },
    ],
  },
  {
    id: 'orders-bookings',
    label: 'Sales & Customers',
    icon: 'receipt_long',
    group: 'orders',
    children: [
      {
        label: 'Orders',
        icon: 'list_alt',
        route: '/orders',
        permission: PERMISSIONS.ORDER_READ,
      },
      {
        label: 'Bookings',
        icon: 'event_note',
        route: '/bookings',
        permission: PERMISSIONS.BOOKING_READ,
      },
      {
        label: 'Customer',
        icon: 'people',
        route: '/customers',
        permission: PERMISSIONS.CUSTOMER_READ,
      },
    ],
  },
  {
    id: 'dispatch-safety',
    label: 'Operation',
    icon: 'route',
    group: 'dispatch',
    children: [
      {
        label: 'Dispatch List',
        icon: 'list',
        route: '/dispatches',
        permission: PERMISSIONS.DISPATCH_LIST,
      },
      {
        label: 'Dispatch Planning',
        icon: 'alt_route',
        route: '/dispatch/planning',
        permission: PERMISSIONS.DISPATCH_CREATE,
      },
      {
        label: 'Dispatch Monitoring',
        icon: 'monitor',
        route: '/dispatch/monitor',
        permission: PERMISSIONS.DISPATCH_MONITOR,
      },
      {
        label: 'Loading Management (KHB)',
        icon: 'inventory_2',
        route: '/dispatch/loading-khb',
        permission: PERMISSIONS.DISPATCH_READ,
      },
      {
        label: 'Loading Monitor (POD)',
        icon: 'photo_camera',
        route: '/dispatch/loading-monitor',
        permission: PERMISSIONS.POD_READ,
      },
      {
        label: 'Bulk Order Upload',
        icon: 'cloud_upload',
        route: '/orders/upload',
        permission: PERMISSIONS.SHIPMENT_UPLOAD,
      },
      {
        label: 'Pre-Entry Safety',
        icon: 'health_and_safety',
        route: '/dispatch/pre-entry-safety',
        permission: PERMISSIONS.DISPATCH_MONITOR,
      },
    ],
  },
  {
    id: 'live-tracking',
    label: 'Live Tracking',
    icon: 'sensors',
    group: 'live',
    children: [
      {
        label: 'Live Map',
        icon: 'map',
        route: '/live/map',
        permission: [PERMISSIONS.TELEMATICS_LIVE_READ, PERMISSIONS.DRIVER_LIVE_READ],
      },
      {
        label: 'Geofences',
        icon: 'fence',
        route: '/live/geofences',
        permission: [PERMISSIONS.TELEMATICS_GEOFENCE_READ, PERMISSIONS.GEOFENCE_READ],
      },
      {
        label: 'Telematics Console',
        icon: 'terminal',
        route: '/live/console',
        permission: [PERMISSIONS.TELEMATICS_CONSOLE_READ, PERMISSIONS.ADMIN_READ],
      },
    ],
  },
  {
    id: 'fleet-drivers',
    label: 'Fleet & Drivers',
    icon: 'local_shipping',
    group: 'fleet',
    children: [
      {
        label: 'Drivers',
        icon: 'people',
        route: '/fleet/drivers',
        permission: PERMISSIONS.DRIVER_LIST,
      },
      {
        label: 'Driver Documents',
        icon: 'description',
        route: '/fleet/drivers/documents',
        permission: PERMISSIONS.DRIVER_DOCUMENT_READ,
      },
      {
        label: 'Driver Accounts',
        icon: 'account_circle',
        route: '/fleet/drivers/accounts',
        permission: PERMISSIONS.DRIVER_ACCOUNT_READ,
      },
      {
        label: 'Driver Groups',
        icon: 'group_work',
        route: '/fleet/drivers/groups',
        permission: PERMISSIONS.DRIVER_MANAGE,
      },
      {
        label: 'Driver Performance',
        icon: 'analytics',
        route: '/fleet/drivers/performance',
        permission: PERMISSIONS.DRIVER_PERFORMANCE_READ,
      },
      {
        label: 'Driver Devices',
        icon: 'devices',
        route: '/fleet/drivers/devices',
        permission: PERMISSIONS.DRIVER_DEVICE_READ,
      },
      {
        label: 'Driver Attendance',
        icon: 'event_available',
        route: '/fleet/drivers/attendance',
        permission: PERMISSIONS.DRIVER_ATTENDANCE_READ,
      },
      {
        label: 'Driver Chat',
        icon: 'forum',
        route: '/drivers/communication/messages',
        permission: [PERMISSIONS.DRIVER_MESSAGES_READ, PERMISSIONS.ADMIN_READ],
      },
      {
        label: 'Vehicles',
        icon: 'directions_car',
        route: '/fleet/vehicles',
        permission: PERMISSIONS.VEHICLE_READ,
      },
      {
        label: 'Vehicle Documents',
        icon: 'folder',
        route: '/fleet/vehicles/documents',
        permission: PERMISSIONS.VEHICLE_READ,
      },
      {
        label: 'Vehicle Assignments',
        icon: 'assignment_ind',
        route: '/fleet/vehicles/assignments',
        permission: [PERMISSIONS.VEHICLE_UPDATE, PERMISSIONS.DRIVER_MANAGE],
      },
      {
        label: 'Compliance & Training',
        icon: 'workspace_premium',
        permission: PERMISSIONS.ADMIN_READ,
        children: [
          {
            label: 'Document Compliance',
            icon: 'fact_check',
            route: '/compliance',
            permission: PERMISSIONS.ADMIN_READ,
          },
          {
            label: 'Training Records',
            icon: 'school',
            route: '/training',
            permission: PERMISSIONS.ADMIN_READ,
          },
          {
            label: 'Expiring Training',
            icon: 'schedule',
            route: '/training/expiring',
            permission: PERMISSIONS.ADMIN_READ,
          },
        ],
      },
      {
        id: 'fleet-maintenance',
        label: 'Maintenance',
        icon: 'build_circle',
        permission: [
          PERMISSIONS.MAINTENANCE_READ,
          PERMISSIONS.MAINTENANCE_PM_READ,
          PERMISSIONS.MAINTENANCE_WORKORDER_READ,
          PERMISSIONS.MAINTENANCE_RECORD_READ,
          PERMISSIONS.MAINTENANCE_SCHEDULE_READ,
          PERMISSIONS.MAINTENANCE_REPAIR_READ,
          PERMISSIONS.MAINTENANCE_PART_READ,
          PERMISSIONS.MAINTENANCE_FAILURE_CODE_READ,
        ],
        children: [
          {
            label: 'Overview',
            icon: 'dashboard',
            route: '/fleet/maintenance/dashboard',
            permission: PERMISSIONS.MAINTENANCE_READ,
          },
          {
            label: 'Requests',
            icon: 'assignment',
            route: '/fleet/maintenance/requests',
            permission: PERMISSIONS.MAINTENANCE_READ,
          },
          {
            label: 'Work Orders',
            icon: 'assignment_turned_in',
            route: '/fleet/maintenance/work-orders',
            permission: PERMISSIONS.MAINTENANCE_WORKORDER_READ,
          },
          {
            label: 'Repairs',
            icon: 'handyman',
            route: '/fleet/maintenance/repairs',
            permission: PERMISSIONS.MAINTENANCE_REPAIR_READ,
          },
          {
            label: 'Records',
            icon: 'history',
            route: '/fleet/maintenance/records',
            permission: PERMISSIONS.MAINTENANCE_RECORD_READ,
          },
          {
            label: 'Schedule',
            icon: 'calendar_month',
            route: '/fleet/maintenance/schedule',
            permission: PERMISSIONS.MAINTENANCE_SCHEDULE_READ,
          },
          {
            label: 'PM',
            icon: 'event_repeat',
            permission: PERMISSIONS.MAINTENANCE_PM_READ,
            children: [
              {
                label: 'Overview',
                icon: 'dashboard_customize',
                route: '/fleet/maintenance/pm-dashboard',
                permission: PERMISSIONS.MAINTENANCE_PM_READ,
              },
              {
                label: 'Plans',
                icon: 'fact_check',
                route: '/fleet/maintenance/pm-plans',
                permission: PERMISSIONS.MAINTENANCE_PM_READ,
              },
              {
                label: 'Runs',
                icon: 'play_circle',
                route: '/fleet/maintenance/pm-runs',
                permission: PERMISSIONS.MAINTENANCE_PM_READ,
              },
              {
                label: 'Calendar',
                icon: 'calendar_today',
                route: '/fleet/maintenance/pm-calendar',
                permission: PERMISSIONS.MAINTENANCE_PM_READ,
              },
              {
                label: 'Reports',
                icon: 'assessment',
                route: '/fleet/maintenance/pm-reports',
                permission: PERMISSIONS.MAINTENANCE_PM_READ,
              },
            ],
          },
          {
            label: 'Workshop',
            icon: 'garage',
            route: '/fleet/maintenance/pm-workshop',
            permission: PERMISSIONS.MAINTENANCE_WORKORDER_READ,
          },
          {
            label: 'Inventory',
            icon: 'inventory',
            route: '/fleet/maintenance/parts',
            permission: PERMISSIONS.MAINTENANCE_PART_READ,
          },
        ],
      },
      {
        id: 'fleet-advanced',
        label: 'Advanced',
        icon: 'tune',
        isAdvanced: true,
        children: [
          {
            label: 'Assign Truck to Driver',
            icon: 'assignment_ind',
            route: '/fleet/assign-truck-driver',
            permission: [PERMISSIONS.VEHICLE_UPDATE, PERMISSIONS.DRIVER_MANAGE],
            isAdvanced: true,
          },
          {
            label: 'Truck-Driver Assignments',
            icon: 'view_list',
            route: '/fleet/truck-driver-assignments',
            permission: [PERMISSIONS.VEHICLE_UPDATE, PERMISSIONS.DRIVER_MANAGE],
            isAdvanced: true,
          },
          {
            label: 'Driver Overview (Alias)',
            icon: 'insights',
            route: '/drivers/overview',
            permission: PERMISSIONS.DRIVER_READ,
            isAdvanced: true,
          },
          {
            label: 'Driver Module List (Alias)',
            icon: 'badge',
            route: '/drivers/list',
            permission: PERMISSIONS.DRIVER_READ,
            isAdvanced: true,
          },
        ],
      },
    ],
  },
  {
    id: 'master-data',
    label: 'Master Data',
    icon: 'dataset',
    group: 'master-data',
    children: [
      {
        label: 'Customers',
        icon: 'people',
        route: '/customers',
        permission: PERMISSIONS.CUSTOMER_READ,
      },
      {
        label: 'Vendors',
        icon: 'business',
        route: '/vendors',
        permission: PERMISSIONS.VENDOR_READ,
      },
      {
        label: 'Subcontractors',
        icon: 'handshake',
        route: '/subcontractors',
        permission: PERMISSIONS.SUBCONTRACTOR_READ,
      },
      {
        label: 'Subcontractor Admins',
        icon: 'supervisor_account',
        route: '/subcontractors/admins',
        permission: PERMISSIONS.SUBCONTRACTOR_ADMIN_READ,
      },
      {
        label: 'Items',
        icon: 'inventory_2',
        route: '/items',
        permission: PERMISSIONS.ITEM_READ,
      },
      {
        label: 'ប្រភេទសុវត្ថិភាព',
        icon: 'category',
        route: '/safety/master/categories',
        permission: PERMISSIONS.ADMIN_READ,
      },
      {
        label: 'ធាតុត្រួតពិនិត្យសុវត្ថិភាព',
        icon: 'rule',
        route: '/safety/master/items',
        permission: PERMISSIONS.ADMIN_READ,
      },
      {
        label: 'Failure Codes',
        icon: 'report_problem',
        route: '/fleet/maintenance/failure-codes',
        permission: PERMISSIONS.MAINTENANCE_FAILURE_CODE_READ,
      },
      {
        label: 'Pre-entry Category',
        icon: 'category',
        route: '/admin/pre-entry-master/categories',
        permission: PERMISSIONS.ADMIN_READ,
      },
      {
        label: 'Pre-entry Item',
        icon: 'fact_check',
        route: '/admin/pre-entry-master/items',
        permission: PERMISSIONS.ADMIN_READ,
      },
    ],
  },
  {
    id: 'partners-operations',
    label: 'Support & Compliance',
    icon: 'business_center',
    group: 'partners',
    children: [
      {
        label: 'Daily Safety',
        icon: 'verified_user',
        route: '/safety',
        permission: PERMISSIONS.DISPATCH_READ,
      },
      {
        label: 'Incidents',
        icon: 'assignment_late',
        route: '/incidents/list',
        permission: PERMISSIONS.INCIDENT_READ,
      },
      {
        label: 'Cases',
        icon: 'folder_special',
        route: '/cases/list',
        permission: PERMISSIONS.CASE_READ,
      },
      {
        label: 'Tasks',
        icon: 'task',
        route: '/tasks',
        permission: [PERMISSIONS.TASK_READ, PERMISSIONS.ADMIN_READ],
      },
      {
        id: 'partners-advanced',
        label: 'Advanced',
        icon: 'tune',
        isAdvanced: true,
        children: [
          {
            label: 'Subcontractor Metrics',
            icon: 'query_stats',
            route: '/subcontractors/metrics',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'Subcontractor Compliance',
            icon: 'verified',
            route: '/subcontractors/compliance',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'Subcontractor Finance',
            icon: 'account_balance',
            route: '/subcontractors/finance',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'Legacy Maintenance Tasks',
            icon: 'history',
            route: '/tasks/maintenance/list',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
        ],
      },
    ],
  },
  {
    id: 'admin-settings',
    label: 'Admin & Settings',
    icon: 'admin_panel_settings',
    group: 'admin',
    children: [
      {
        label: 'Dispatch Day Report',
        icon: 'calendar_view_day',
        route: '/reports/dispatch/day',
        permission: PERMISSIONS.REPORT_DISPATCH_DAY,
      },
      {
        label: 'User Management',
        icon: 'people',
        route: '/admin',
        permission: PERMISSIONS.ADMIN_USER_READ,
      },
      {
        label: 'Employees',
        icon: 'badge',
        route: '/admin/employees',
        permission: PERMISSIONS.ADMIN_USER_READ,
      },
      {
        label: 'Roles',
        icon: 'group',
        route: '/admin/roles',
        permission: PERMISSIONS.ADMIN_ROLE_READ,
      },
      {
        label: 'Permissions',
        icon: 'security',
        route: '/admin/permissions',
        permission: PERMISSIONS.ADMIN_PERMISSION_READ,
      },
      {
        id: 'notifications',
        label: 'Notifications',
        icon: 'notifications',
        route: '/admin/notifications',
        permission: PERMISSIONS.NOTIFICATION_READ,
      },
      {
        label: 'Notification Settings',
        icon: 'tune',
        route: '/admin/notification-settings',
        permission: PERMISSIONS.SETTING_NOTIFICATIONS_READ,
      },
      {
        label: 'Banner Management',
        icon: 'campaign',
        route: '/banners',
        permission: PERMISSIONS.BANNER_READ,
      },
      {
        label: 'Driver App Hub',
        icon: 'phone_android',
        route: '/settings/driver-app',
        permission: PERMISSIONS.SETTING_READ,
      },
      {
        label: 'App Version & Updates',
        icon: 'system_update',
        route: '/settings/driver-app/version',
        permission: PERMISSIONS.SETTING_READ,
      },
      {
        label: 'Module & Feature Toggles',
        icon: 'app_settings_alt',
        route: '/settings/app-management',
        permission: PERMISSIONS.SETTING_READ,
      },
      {
        label: 'Home Layout Management',
        icon: 'view_module',
        route: '/settings/home-layout',
        permission: PERMISSIONS.HOME_LAYOUT_MANAGE,
      },
      {
        label: 'System Core',
        icon: 'settings_applications',
        route: '/settings/group/system.core',
        permission: PERMISSIONS.SETTING_SYSTEM_CORE_READ,
      },
      {
        label: 'Security & Auth',
        icon: 'admin_panel_settings',
        route: '/settings/group/security.auth',
        permission: PERMISSIONS.SETTING_SECURITY_AUTH_READ,
      },
      {
        label: 'Feature Flags',
        icon: 'flag',
        route: '/settings/group/feature.flags',
        permission: PERMISSIONS.SETTING_FEATURE_FLAGS_READ,
      },
      {
        label: 'Google Maps',
        icon: 'map',
        route: '/settings/group/maps.google',
        permission: PERMISSIONS.SETTING_MAPS_GOOGLE_READ,
      },
      {
        label: 'Uploads & Storage',
        icon: 'cloud_upload',
        route: '/settings/group/uploads.storage',
        permission: PERMISSIONS.SETTING_UPLOADS_STORAGE_READ,
      },
      {
        label: 'Finance',
        icon: 'account_balance',
        route: '/settings/group/finance',
        permission: PERMISSIONS.SETTING_FINANCE_READ,
      },
      {
        label: 'Branding & Theme',
        icon: 'palette',
        route: '/settings/group/branding.theme',
        permission: PERMISSIONS.SETTING_BRANDING_THEME_READ,
      },
      {
        label: 'i18n / Locale',
        icon: 'language',
        route: '/settings/group/i18n.locale',
        permission: PERMISSIONS.SETTING_I18N_LOCALE_READ,
      },
      {
        label: 'Settings Audit Log',
        icon: 'history',
        route: '/settings/audit',
        permission: PERMISSIONS.SETTING_AUDIT_READ,
      },
      {
        label: 'Import / Export',
        icon: 'import_export',
        route: '/settings/import-export',
        permission: PERMISSIONS.SETTING_IMPORT_EXPORT_READ,
      },
      {
        label: 'Create Setting',
        icon: 'add_circle',
        route: '/settings/create',
        permission: PERMISSIONS.SETTING_CREATE,
      },
      {
        label: 'Dispatch Flow Policy',
        icon: 'account_tree',
        route: '/settings/dispatch-flow',
        permission: PERMISSIONS.DISPATCH_FLOW_MANAGE,
      },
      {
        id: 'admin-advanced',
        label: 'Advanced',
        icon: 'tune',
        isAdvanced: true,
        children: [
          {
            label: 'Token Management',
            icon: 'key',
            route: '/admin/tokens',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'Dynamic Permissions',
            icon: 'admin_panel_settings',
            route: '/admin/dynamic-permissions',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'System Initialization',
            icon: 'settings_suggest',
            route: '/admin/system-initialization',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'Audit Trails',
            icon: 'manage_search',
            route: '/admin/audit-trails',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'SO Upload',
            icon: 'upload',
            route: '/admin/uploads/so',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'KHB Upload',
            icon: 'upload_file',
            route: '/admin/uploads/khb',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
          {
            label: 'KHB Trip Pre-Plan',
            icon: 'route',
            route: '/admin/uploads/khb/trip-pre-plan',
            permission: PERMISSIONS.ADMIN_READ,
            isAdvanced: true,
          },
        ],
      },
    ],
  },
];
