spring.config.import=optional:classpath:application-backend-common.properties
spring.application.name=tms-auth-api
server.port=${SERVER_PORT:8083}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.health.mongo.enabled=false
