-- V1: Create core telematics tables on PostgreSQL.

CREATE TABLE IF NOT EXISTS driver_latest_location (
    driver_id        BIGINT PRIMARY KEY,
    latitude         DOUBLE PRECISION NOT NULL DEFAULT 0,
    longitude        DOUBLE PRECISION NOT NULL DEFAULT 0,
    speed            DOUBLE PRECISION,
    heading          DOUBLE PRECISION,
    dispatch_id      BIGINT,
    last_seen        TIMESTAMP(6),
    is_online        BOOLEAN,
    ws_connected     BOOLEAN NOT NULL DEFAULT FALSE,
    battery_level    INTEGER,
    location_name    VARCHAR(255),
    source           VARCHAR(32),
    version          BIGINT,
    accuracy_meters  DOUBLE PRECISION,
    location_source  VARCHAR(16),
    net_type         VARCHAR(16)
);

CREATE INDEX IF NOT EXISTS idx_dll_online ON driver_latest_location (is_online);
CREATE INDEX IF NOT EXISTS idx_dll_last_seen ON driver_latest_location (last_seen);
CREATE INDEX IF NOT EXISTS idx_dll_online_lastseen ON driver_latest_location (is_online, last_seen);
CREATE INDEX IF NOT EXISTS idx_dll_dispatch_id ON driver_latest_location (dispatch_id);

CREATE TABLE IF NOT EXISTS location_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_id        BIGINT NOT NULL,
    dispatch_id      BIGINT,
    latitude         DOUBLE PRECISION NOT NULL,
    longitude        DOUBLE PRECISION NOT NULL,
    location_name    VARCHAR(512),
    event_time       TIMESTAMP(6) NOT NULL,
    timestamp        TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6),
    is_online        BOOLEAN NOT NULL DEFAULT FALSE,
    speed            DOUBLE PRECISION,
    battery_level    INTEGER,
    source           VARCHAR(50),
    heading          DOUBLE PRECISION,
    accuracy_meters  DOUBLE PRECISION,
    location_source  VARCHAR(16),
    net_type         VARCHAR(16),
    app_version_code BIGINT,
    point_id         VARCHAR(64),
    seq              BIGINT,
    session_id       VARCHAR(64),
    PRIMARY KEY (event_time, id)
) PARTITION BY RANGE (event_time);

CREATE TABLE IF NOT EXISTS location_history_default
    PARTITION OF location_history DEFAULT;

CREATE INDEX IF NOT EXISTS idx_lh_driver_event ON location_history (driver_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_lh_dispatch_event ON location_history (dispatch_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_lh_session ON location_history (session_id);
CREATE INDEX IF NOT EXISTS idx_lh_point_id ON location_history (point_id);

CREATE TABLE IF NOT EXISTS driver_tracking_sessions (
    session_id  VARCHAR(64) PRIMARY KEY,
    driver_id   BIGINT NOT NULL,
    device_id   VARCHAR(128) NOT NULL,
    issued_at   TIMESTAMP(6) NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    revoked_at  TIMESTAMP(6),
    last_seen   TIMESTAMP(6),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dts_driver ON driver_tracking_sessions (driver_id);
CREATE INDEX IF NOT EXISTS idx_dts_expires ON driver_tracking_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_dts_driver_active
    ON driver_tracking_sessions (driver_id, expires_at, revoked_at);
