-- V2: Spoofing alerts table (persists the TODO alerts from tms-backend)

CREATE TABLE IF NOT EXISTS spoofing_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id       BIGINT          NOT NULL,
    dispatch_id     BIGINT,
    session_id      VARCHAR(64),
    alert_type      VARCHAR(64)     NOT NULL,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    speed_kmh       DOUBLE PRECISION,
    distance_meters DOUBLE PRECISION,
    time_delta_ms   BIGINT,
    detail          VARCHAR(1024),
    device_id       VARCHAR(128),
    created_at      TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sa_driver ON spoofing_alerts (driver_id);
CREATE INDEX IF NOT EXISTS idx_sa_created ON spoofing_alerts (created_at);
CREATE INDEX IF NOT EXISTS idx_sa_session ON spoofing_alerts (session_id);
CREATE INDEX IF NOT EXISTS idx_sa_type ON spoofing_alerts (alert_type);
