-- V5: strengthen telematics ingest contract with durable freshness timestamps
-- and DB-level idempotency guards.

ALTER TABLE driver_latest_location
    ADD COLUMN IF NOT EXISTS last_received_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS last_event_time TIMESTAMP(6);

UPDATE driver_latest_location
SET last_received_at = COALESCE(last_received_at, last_seen),
    last_event_time = COALESCE(last_event_time, last_seen)
WHERE last_received_at IS NULL
   OR last_event_time IS NULL;

CREATE INDEX IF NOT EXISTS idx_dll_last_received_at
    ON driver_latest_location (last_received_at);

CREATE INDEX IF NOT EXISTS idx_dll_online_last_received
    ON driver_latest_location (is_online, last_received_at);

CREATE TABLE IF NOT EXISTS telematics_ingest_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    point_id VARCHAR(64),
    session_id VARCHAR(64),
    seq BIGINT,
    client_time TIMESTAMP(6),
    received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tir_driver_point_id
    ON telematics_ingest_receipt (driver_id, point_id)
    WHERE point_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tir_driver_session_seq
    ON telematics_ingest_receipt (driver_id, session_id, seq)
    WHERE session_id IS NOT NULL AND seq IS NOT NULL;
