#!/usr/bin/env bash
# =============================================================================
# VPS Bootstrap — One-Time Setup via Password Auth
# =============================================================================
# Run this ONCE from your local machine to:
#   1. Install Docker + Docker Compose on the VPS
#   2. Create a dedicated deploy user (svtms-deploy)
#   3. Install the GitHub Actions SSH public key
#   4. Set up /opt/sv-tms directory structure
#   5. Copy infra files to the VPS
#   6. Harden SSH (disable root password login)
#
# Prerequisites (local machine):
#   apt install sshpass   # or: brew install hudochenkov/sshpass/sshpass
#
# Usage:
#   chmod +x deploy/vps_bootstrap.sh
#   ./deploy/vps_bootstrap.sh
# =============================================================================
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
VPS_HOST="${VPS_HOST:-207.180.245.156}"
VPS_PORT="${VPS_PORT:-22}"
VPS_ROOT_USER="${VPS_ROOT_USER:-root}"
VPS_ROOT_PASS="${VPS_ROOT_PASS:-}"          # set via env var, not here
DEPLOY_USER="svtms-deploy"
DEPLOY_DIR="/opt/sv-tms"

# Path to the GitHub Actions public key generated by vps_keygen.sh
DEPLOY_PUBKEY_FILE="${DEPLOY_PUBKEY_FILE:-$(dirname "$0")/../infra/deploy_key.pub}"
# ──────────────────────────────────────────────────────────────────────────────

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Checks ────────────────────────────────────────────────────────────────────
if ! command -v sshpass >/dev/null 2>&1; then
  error "sshpass is required. Install with: apt install sshpass  (or brew install hudochenkov/sshpass/sshpass)"
fi

if [[ -z "${VPS_ROOT_PASS:-}" ]]; then
  read -rsp "Enter root password for ${VPS_HOST}: " VPS_ROOT_PASS
  echo
fi

if [[ ! -f "${DEPLOY_PUBKEY_FILE}" ]]; then
  error "Deploy public key not found at ${DEPLOY_PUBKEY_FILE}. Run: cat infra/deploy_key.pub"
fi

PUBKEY_CONTENT="$(cat "${DEPLOY_PUBKEY_FILE}")"

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${VPS_PORT}"
SSHPASS_CMD="sshpass -p ${VPS_ROOT_PASS} ssh ${SSH_OPTS}"
SCP_CMD="sshpass -p ${VPS_ROOT_PASS} scp -P ${VPS_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

run_remote() {
  ${SSHPASS_CMD} "${VPS_ROOT_USER}@${VPS_HOST}" "$@"
}

# ── Step 1: Update system + install Docker ─────────────────────────────────────
info "Step 1/6 — Installing Docker on VPS..."
run_remote bash <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq

# Install Docker if not present
if ! command -v docker >/dev/null 2>&1; then
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
  echo "Docker installed: $(docker --version)"
else
  echo "Docker already installed: $(docker --version)"
fi

# Install useful tools
apt-get install -y -qq git curl rsync ufw fail2ban unattended-upgrades
REMOTE

# ── Step 2: Create deploy user ─────────────────────────────────────────────────
info "Step 2/6 — Creating deploy user (${DEPLOY_USER})..."
run_remote bash -s -- "${DEPLOY_USER}" "${DEPLOY_DIR}" "${PUBKEY_CONTENT}" <<'REMOTE'
set -euo pipefail
DEPLOY_USER="$1"
DEPLOY_DIR="$2"
PUBKEY="$3"

# Create user if not exists
if ! id "${DEPLOY_USER}" &>/dev/null; then
  useradd -m -s /bin/bash "${DEPLOY_USER}"
  echo "User ${DEPLOY_USER} created."
fi

# Add to docker group
usermod -aG docker "${DEPLOY_USER}"

# Setup SSH authorized_keys
install -d -m 700 "/home/${DEPLOY_USER}/.ssh"
echo "${PUBKEY}" > "/home/${DEPLOY_USER}/.ssh/authorized_keys"
chmod 600 "/home/${DEPLOY_USER}/.ssh/authorized_keys"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "/home/${DEPLOY_USER}/.ssh"

# Allow sudo for docker compose operations (no password)
echo "${DEPLOY_USER} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/bin/docker compose" \
  > "/etc/sudoers.d/${DEPLOY_USER}"
chmod 440 "/etc/sudoers.d/${DEPLOY_USER}"
echo "Deploy user ${DEPLOY_USER} configured."
REMOTE

# ── Step 3: Create directory structure ────────────────────────────────────────
info "Step 3/6 — Creating directory structure at ${DEPLOY_DIR}..."
run_remote bash -s -- "${DEPLOY_DIR}" "${DEPLOY_USER}" <<'REMOTE'
set -euo pipefail
DEPLOY_DIR="$1"
DEPLOY_USER="$2"

mkdir -p "${DEPLOY_DIR}"/{infra,releases,backups}
mkdir -p /srv/svtms/{mysql,postgres,redis,mongo,uploads,uploads-init,telematics-spool,message-api,certs,webroot}
mkdir -p /srv/svtms/monitoring/{prometheus,grafana,alertmanager}

# Set ownership
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${DEPLOY_DIR}"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" /srv/svtms

echo "Directories created."
REMOTE

# ── Step 4: Copy infra files ──────────────────────────────────────────────────
info "Step 4/6 — Copying infra files to VPS..."
INFRA_DIR="$(dirname "$0")/../infra"

${SCP_CMD} -r \
  "${INFRA_DIR}/docker-compose.prod.yml" \
  "${INFRA_DIR}/nginx" \
  "${INFRA_DIR}/monitoring" \
  "${VPS_ROOT_USER}@${VPS_HOST}:${DEPLOY_DIR}/infra/"

# Copy .env if it exists, otherwise copy example
if [[ -f "${INFRA_DIR}/.env" ]]; then
  warn ".env found locally — copying to VPS (verify secrets are correct!)"
  ${SCP_CMD} "${INFRA_DIR}/.env" "${VPS_ROOT_USER}@${VPS_HOST}:${DEPLOY_DIR}/infra/.env"
else
  ${SCP_CMD} "${INFRA_DIR}/.env.example" "${VPS_ROOT_USER}@${VPS_HOST}:${DEPLOY_DIR}/infra/.env.example"
  warn "No .env found. Copied .env.example to ${DEPLOY_DIR}/infra/.env.example"
  warn "You MUST create ${DEPLOY_DIR}/infra/.env on the VPS before deploying!"
fi

# ── Step 5: Configure UFW firewall ────────────────────────────────────────────
info "Step 5/6 — Configuring firewall..."
run_remote bash <<'REMOTE'
set -euo pipefail
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow "${VPS_PORT:-22}/tcp" comment 'SSH'
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'
ufw --force enable
echo "Firewall configured."
REMOTE

# ── Step 6: Harden SSH ────────────────────────────────────────────────────────
info "Step 6/6 — Hardening SSH (disabling root password login)..."
run_remote bash -s -- "${DEPLOY_USER}" <<'REMOTE'
set -euo pipefail
DEPLOY_USER="$1"

# Disable root password auth & password auth entirely
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

# Make sure deploy user can still SSH in
grep -qF "AllowUsers" /etc/ssh/sshd_config \
  || echo "AllowUsers root ${DEPLOY_USER}" >> /etc/ssh/sshd_config

systemctl reload sshd
echo "SSH hardened. Password auth disabled."
REMOTE

# ── Done ──────────────────────────────────────────────────────────────────────
info "Bootstrap complete!"
echo ""
echo -e "${YELLOW}=== NEXT STEPS ===${NC}"
echo ""
echo "1. Create /opt/sv-tms/infra/.env on the VPS:"
echo "   ssh ${DEPLOY_USER}@${VPS_HOST} -i infra/deploy_key"
echo "   nano /opt/sv-tms/infra/.env"
echo "   (copy from infra/.env.example and fill in all secrets)"
echo ""
echo "2. Add these secrets to GitHub repository settings:"
echo "   Settings → Secrets → Actions → New repository secret"
echo ""
echo "   PROD_DEPLOY_HOST   = ${VPS_HOST}"
echo "   PROD_DEPLOY_USER   = ${DEPLOY_USER}"
echo "   PROD_DEPLOY_SSH_KEY = (content of infra/deploy_key)"
echo ""
echo "3. Push to main branch to trigger auto-deploy, or:"
echo "   gh workflow run deploy-vps.yml"
echo ""
echo -e "${GREEN}VPS is ready at ${VPS_HOST}${NC}"
