-- Add missing safety and queue statuses to dispatches and history
ALTER TABLE dispatches 
  MODIFY status ENUM('PENDING','ASSIGNED','DRIVER_CONFIRMED','APPROVED','REJECTED','SCHEDULED','ARRIVED_LOADING','LOADING','LOADED','SAFETY_PASSED','SAFETY_FAILED','IN_QUEUE','IN_TRANSIT','ARRIVED_UNLOADING','UNLOADING','UNLOADED','DELIVERED','COMPLETED','CANCELLED') NULL;

ALTER TABLE dispatch_status_history 
  MODIFY status ENUM('PENDING','ASSIGNED','DRIVER_CONFIRMED','APPROVED','REJECTED','SCHEDULED','ARRIVED_LOADING','LOADING','LOADED','SAFETY_PASSED','SAFETY_FAILED','IN_QUEUE','IN_TRANSIT','ARRIVED_UNLOADING','UNLOADING','UNLOADED','DELIVERED','COMPLETED','CANCELLED') NULL;
