-- ============================================================================
-- V502: ensure work_orders table exists for maintenance module
-- ============================================================================
CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    wo_number VARCHAR(50) NOT NULL,
    vehicle_id BIGINT NOT NULL,
    issue_summary TEXT,
    title VARCHAR(200),
    description TEXT,
    notes TEXT,
    status ENUM('OPEN','IN_PROGRESS','WAITING_PARTS','COMPLETED','CANCELLED') NOT NULL DEFAULT 'OPEN',
    type ENUM('PREVENTIVE','REPAIR','EMERGENCY','INSPECTION') NOT NULL,
    priority ENUM('URGENT','HIGH','NORMAL','LOW') NOT NULL DEFAULT 'NORMAL',
    assigned_technician_id BIGINT,
    supervisor_id BIGINT,
    scheduled_date DATETIME,
    started_at DATETIME,
    completed_at DATETIME,
    labor_cost DECIMAL(10,2) DEFAULT 0,
    parts_cost DECIMAL(10,2) DEFAULT 0,
    total_cost DECIMAL(10,2) DEFAULT 0,
    estimated_cost DECIMAL(10,2),
    actual_cost DECIMAL(10,2),
    remarks TEXT,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by BIGINT,
    approved_at DATETIME,
    approval_remarks TEXT,
    rejection_reason TEXT,
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    breakdown_location VARCHAR(500),
    breakdown_latitude DECIMAL(10,8),
    breakdown_longitude DECIMAL(11,8),
    breakdown_reported_at DATETIME,
    technician_dispatched_at DATETIME,
    technician_arrived_at DATETIME,
    downtime_minutes INT,
    pm_schedule_id BIGINT,
    driver_issue_id BIGINT,
    maintenance_task_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE KEY uk_work_orders_number (wo_number),
    INDEX idx_work_orders_vehicle (vehicle_id),
    INDEX idx_work_orders_status (status),
    INDEX idx_work_orders_created (created_at),
    CONSTRAINT fk_work_orders_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_work_orders_assigned_technician FOREIGN KEY (assigned_technician_id) REFERENCES users(id),
    CONSTRAINT fk_work_orders_supervisor FOREIGN KEY (supervisor_id) REFERENCES users(id),
    CONSTRAINT fk_work_orders_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_work_orders_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_work_orders_driver_issue FOREIGN KEY (driver_issue_id) REFERENCES driver_issues(id),
    CONSTRAINT fk_work_orders_pm_schedule FOREIGN KEY (pm_schedule_id) REFERENCES pm_schedules(id),
    CONSTRAINT fk_work_orders_maintenance_task FOREIGN KEY (maintenance_task_id) REFERENCES maintenance_task_types(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
