/**
 * SV-TMS Public API (Customer)
 * Public subset of the SV-TMS API used by the customer mobile app (customer_app). Contains endpoints for orders and addresses.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Address {
  id?: number;
  label?: string;
  street?: string;
  city?: string;
  postalCode?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
}
