/**
 * SV-TMS Public API (Customer)
 * Public subset of the SV-TMS API used by the customer mobile app (customer_app). Contains endpoints for orders and addresses.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Address } from './address';

export interface Order {
  id: number;
  customerId: number;
  status: string;
  pickupAddress?: Address;
  deliveryAddress?: Address;
  createdAt?: string;
}
