/**
 * Playwright Global Teardown
 * Runs once after all tests to cleanup test environment
 */

import { FullConfig } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

async function globalTeardown(config: FullConfig) {
  console.log('\n🧹 Starting global test teardown...');

  const apiBaseUrl = process.env['API_BASE_URL'] || 'http://localhost:8080';

  // 1. Cleanup test database
  console.log('🗄️  Cleaning up test database...');
  await cleanupDatabase(apiBaseUrl);
  console.log('Test database cleaned');

  // 2. Remove authentication state files
  console.log('🔐 Removing authentication state...');
  cleanupAuthState();
  console.log('Authentication state removed');

  // 3. Generate test summary report
  console.log('📊 Generating test summary...');
  generateTestSummary();
  console.log('Test summary generated');

  console.log('✨ Global teardown complete!\n');
}

/**
 * Cleanup test database
 */
async function cleanupDatabase(apiUrl: string): Promise<void> {
  try {
    const response = await fetch(`${apiUrl}/api/test/cleanup`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' }
    });

    if (!response.ok && response.status !== 404) {
      console.warn('⚠️  Database cleanup endpoint not available, skipping...');
    }
  } catch (error) {
    console.warn('⚠️  Could not cleanup database:', error);
  }
}

/**
 * Remove saved authentication state files
 */
function cleanupAuthState(): void {
  const authDir = path.join(process.cwd(), 'playwright', '.auth');

  try {
    if (fs.existsSync(authDir)) {
      const files = fs.readdirSync(authDir);
      for (const file of files) {
        if (file.endsWith('.json')) {
          fs.unlinkSync(path.join(authDir, file));
        }
      }
    }
  } catch (error) {
    console.warn('⚠️  Could not cleanup auth state:', error);
  }
}

/**
 * Generate test summary report
 */
function generateTestSummary(): void {
  const testResultsDir = path.join(process.cwd(), 'test-results');
  const summaryFile = path.join(testResultsDir, 'summary.txt');

  try {
    if (!fs.existsSync(testResultsDir)) {
      fs.mkdirSync(testResultsDir, { recursive: true });
    }

    const summary = `
Test Execution Summary
=====================
Date: ${new Date().toISOString()}
Environment: ${process.env['NODE_ENV'] || 'test'}
Backend: ${process.env['API_BASE_URL'] || 'http://localhost:8080'}
Frontend: ${process.env['BASE_URL'] || 'http://localhost:4200'}

Test Results:
- See detailed reports in playwright-report/
- See individual test results in test-results/

Artifacts Generated:
- Screenshots: test-results/**/screenshots/
- Videos: test-results/**/videos/
- Traces: test-results/**/traces/

Next Steps:
1. Review failed tests in playwright-report/index.html
2. Check screenshots/videos for visual issues
3. Analyze traces for debugging details
4. Update tests or code as needed

Generated by Playwright Global Teardown
`;

    fs.writeFileSync(summaryFile, summary.trim());
  } catch (error) {
    console.warn('⚠️  Could not generate test summary:', error);
  }
}

export default globalTeardown;
