#!/usr/bin/env bash
set -euo pipefail

# Export backend OpenAPI to api/driver-app-openapi.json using the built JAR
# Usage: ./scripts/export-openapi.sh

ROOT_DIR=$(dirname "$0")/..
JAR="$ROOT_DIR/driver-app/target/driver-app-0.0.1-SNAPSHOT.jar"
OUT="$ROOT_DIR/api/driver-app-openapi.json"

if [ ! -f "$JAR" ]; then
  echo "JAR not found at $JAR. Run ./mvnw clean package in driver-app first." >&2
  exit 1
fi

echo "Starting backend with in-memory H2 to export OpenAPI (profile=export)..."
# allow overriding the port used for export (useful if 8080 is in use)
PORT="${EXPORT_SERVER_PORT:-8080}"
# export SERVER_PORT for frameworks that read env vars
export SERVER_PORT="$PORT"
# Use export profile with in-memory H2 schema generated by Hibernate (no Flyway)
SPRING_DATASOURCE_URL=jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1 \
SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop \
SPRING_FLYWAY_ENABLED=false \
SPRING_TASK_SCHEDULING_ENABLED=false \
APP_INIT_AUDIT=false \
SPRING_PROFILES_ACTIVE=export \
java -Dspring.profiles.active=export \
  -Dspring.jpa.hibernate.ddl-auto=create-drop \
  -Dspring.flyway.enabled=false \
  -Dspring.task.scheduling.enabled=false \
  -Dapp.init-audit=false \
  -Dserver.port="$PORT" \
  -jar "$JAR" &
PID=$!

# ensure the background server is killed if this script exits early
trap 'kill $PID 2>/dev/null || true' EXIT

# Wait for server health. You can override HEALTH_WAIT_SECONDS (default 120)
HEALTH_WAIT_SECONDS=${HEALTH_WAIT_SECONDS:-120}
echo "Waiting for server to start (max ${HEALTH_WAIT_SECONDS}s)"
ATTEMPTS=0
SLEEP_INTERVAL=2
MAX_ATTEMPTS=$((HEALTH_WAIT_SECONDS / SLEEP_INTERVAL))
until curl -sS "http://localhost:${PORT}/actuator/health" >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS+1))
  if [ $ATTEMPTS -ge $MAX_ATTEMPTS ]; then
    echo "Server did not become ready after ${HEALTH_WAIT_SECONDS}s" >&2
    kill $PID || true
    exit 1
  fi
  sleep $SLEEP_INTERVAL
done

# small pause to let other endpoints warm up
sleep 1

API_WAIT_SECONDS=${API_WAIT_SECONDS:-180}
echo "Waiting for /v3/api-docs to become available and non-empty (max ${API_WAIT_SECONDS}s)"
ATT=0
MAX_API_ATT=$((API_WAIT_SECONDS / SLEEP_INTERVAL))
while true; do
  # fetch into a temp file and check content
  TMP_OUT=$(mktemp)
  http_code=$(curl -sS -w "%{http_code}" -o "$TMP_OUT" http://localhost:${PORT}/v3/api-docs || true)
  size=$(wc -c <"$TMP_OUT" || echo 0)
  if [ "$http_code" = "200" ] && [ "$size" -gt 100 ]; then
    # quick sanity: contains the OpenAPI root key
    if grep -q '"openapi"' "$TMP_OUT" 2>/dev/null || grep -q 'openapi' "$TMP_OUT" 2>/dev/null; then
      mv "$TMP_OUT" "$OUT"
      break
    fi
  fi
  rm -f "$TMP_OUT"
  ATT=$((ATT+1))
  if [ $ATT -ge $MAX_API_ATT ]; then
    echo "Timed out waiting for /v3/api-docs to be ready after ${API_WAIT_SECONDS}s" >&2
    kill $PID || true
    exit 1
  fi
  sleep $SLEEP_INTERVAL
done

echo "Exported OpenAPI to $OUT"
kill $PID || true
echo "Server stopped"
