#!/usr/bin/env python3
"""
Generate a SQL migration that truncates drivers and users tables
and inserts accounts from an Excel file. Passwords are hashed with bcrypt
from the provided default password (default: 123456).

Usage:
  python scripts/migrate_drivers.py /path/to/Book1.xlsx --out migrate_drivers.sql

The script expects at minimum a phone number column. Default column names:
  - name: 'name'
  - phone: 'phone'
  - username: 'username' (optional, falls back to phone)

Adjust table and column names using CLI options to match your DB schema.
"""
import argparse
import pandas as pd
import uuid
import bcrypt
from datetime import datetime
import sys


def esc(s: str) -> str:
    if s is None:
        return ''
    return str(s).replace("'", "''")


def make_uuid() -> str:
    return str(uuid.uuid4())


def hash_password(pw: str) -> str:
    return bcrypt.hashpw(pw.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')


def main():
    p = argparse.ArgumentParser(description='Generate SQL to migrate drivers from Excel')
    p.add_argument('excel', help='Path to Excel file (e.g. /Users/.../Book1.xlsx)')
    p.add_argument('--out', default='migrate_drivers.sql', help='Output SQL file')
    p.add_argument('--sheet', default=0, help='Sheet index or name')
    p.add_argument('--name-col', default='name')
    p.add_argument('--phone-col', default='phone')
    p.add_argument('--username-col', default='username')
    p.add_argument('--users-table', default='users')
    p.add_argument('--drivers-table', default='drivers')
    p.add_argument('--default-password', default='123456')
    p.add_argument('--dialect', default='postgres', choices=['postgres', 'mysql'], help='SQL dialect to emit')
    p.add_argument('--users-auto-increment', action='store_true', help='If set for MySQL, do not emit `id` for users and use LAST_INSERT_ID() for driver.user_id')
    args = p.parse_args()

    try:
        df = pd.read_excel(args.excel, sheet_name=args.sheet, engine='openpyxl')
    except Exception as e:
        print('Failed to read Excel:', e, file=sys.stderr)
        sys.exit(2)

    if args.phone_col not in df.columns:
        print(f"Phone column '{args.phone_col}' not found in Excel columns: {list(df.columns)}", file=sys.stderr)
        sys.exit(2)

    now = datetime.utcnow().isoformat(sep=' ', timespec='seconds')
    sql_lines = []
    sql_lines.append('-- Generated by scripts/migrate_drivers.py')
    sql_lines.append(f'-- source: {esc(args.excel)}')

    if args.dialect == 'postgres':
        sql_lines.append('BEGIN;')
        sql_lines.append(f'TRUNCATE TABLE {args.drivers_table} RESTART IDENTITY CASCADE;')
        sql_lines.append(f'TRUNCATE TABLE {args.users_table} RESTART IDENTITY CASCADE;')
        sql_lines.append('')
    else:  # mysql
        sql_lines.append('SET FOREIGN_KEY_CHECKS=0;')
        sql_lines.append(f'TRUNCATE TABLE {args.drivers_table};')
        sql_lines.append(f'TRUNCATE TABLE {args.users_table};')
        sql_lines.append('SET FOREIGN_KEY_CHECKS=1;')
        sql_lines.append('')

    for idx, row in df.iterrows():
        phone = esc(row.get(args.phone_col))
        if not phone:
            print(f'Skipping row {idx}: empty phone', file=sys.stderr)
            continue
        name = esc(row.get(args.name_col, ''))
        username = esc(row.get(args.username_col, phone))

        user_id = make_uuid()
        driver_id = make_uuid()
        pw_hash = esc(hash_password(args.default_password))

        # Insert user row — adjust columns to match your schema if needed
        if args.dialect == 'mysql' and args.users_auto_increment:
            # Do not emit id column; capture LAST_INSERT_ID() into a variable for the driver insert
            sql_lines.append(
                "INSERT INTO {users_table} (username, phone, password, created_at, account_non_expired, account_non_locked, credentials_non_expired, email, enabled) VALUES ('{username}', '{phone}', '{pw}', '{now}', b'1', b'1', b'1', '{email}', b'1');"
                .format(users_table=args.users_table, username=username, phone=phone, pw=pw_hash, now=now, email=esc(username + '@no-email.local'))
            )
            sql_lines.append('SET @last_user_id = LAST_INSERT_ID();')

            # Insert driver row referencing the last inserted user id. Assume drivers.id is auto-increment too (omit id).
            sql_lines.append(
                "INSERT INTO {drivers_table} (user_id, name, phone, created_at) VALUES (@last_user_id, '{name}', '{phone}', '{now}');"
                .format(drivers_table=args.drivers_table, name=name, phone=phone, now=now)
            )
        else:
            # Default behavior: emit UUIDs for id fields
            sql_lines.append(
                "INSERT INTO {users_table} (id, username, phone, password, created_at) VALUES ('{id}', '{username}', '{phone}', '{pw}', '{now}');"
                .format(users_table=args.users_table, id=user_id, username=username, phone=phone, pw=pw_hash, now=now)
            )

            # Insert driver row — adjust columns to match your schema if needed
            sql_lines.append(
                "INSERT INTO {drivers_table} (id, user_id, name, phone, created_at) VALUES ('{id}', '{user_id}', '{name}', '{phone}', '{now}');"
                .format(drivers_table=args.drivers_table, id=driver_id, user_id=user_id, name=name, phone=phone, now=now)
            )

    if args.dialect == 'postgres':
        sql_lines.append('COMMIT;')

    with open(args.out, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(sql_lines))

    print(f'Wrote SQL -> {args.out} (lines: {len(sql_lines)})')


if __name__ == '__main__':
    main()
