-- =============================================================================
-- V20251223: Alter pre_loading_safety_checks
-- - Link checks to loading_sessions and loading_documents (proof)
-- - Add GPS location, client UUID (idempotency) and synced flag for offline retries
-- - Add a CHECK constraint for `result` to reduce freeform values
-- =============================================================================

ALTER TABLE pre_loading_safety_checks
  ADD COLUMN loading_session_id BIGINT NULL,
  ADD COLUMN proof_document_id BIGINT NULL,
  ADD COLUMN location_lat DECIMAL(10,7) NULL,
  ADD COLUMN location_lng DECIMAL(10,7) NULL,
  ADD COLUMN client_uuid VARCHAR(36) NULL,
  ADD COLUMN synced BOOLEAN NOT NULL DEFAULT FALSE;

-- Add foreign keys (set NULL on delete to preserve historical checks)
ALTER TABLE pre_loading_safety_checks
  ADD CONSTRAINT fk_preload_loading_session FOREIGN KEY (loading_session_id) REFERENCES loading_sessions(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_preload_proof_document FOREIGN KEY (proof_document_id) REFERENCES loading_documents(id) ON DELETE SET NULL;

-- Indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_preload_loading_session ON pre_loading_safety_checks(loading_session_id);
CREATE INDEX IF NOT EXISTS idx_preload_proof_doc ON pre_loading_safety_checks(proof_document_id);
CREATE INDEX IF NOT EXISTS idx_preload_client_uuid ON pre_loading_safety_checks(client_uuid);

-- Constrain result values at the database level where supported
ALTER TABLE pre_loading_safety_checks
  ADD CONSTRAINT chk_preload_result CHECK (result IN ('PASS','FAIL','RECHECK'));

-- Notes:
--  - `client_uuid` should be generated by the mobile client to make POSTs idempotent.
--  - `synced` can be used by the backend to mark successful server processing of an offline submission.
